// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlspkzyqvwvotdlgccgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsc3Brenlxdnd2b3RkbGdjY2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzcwNDYsImV4cCI6MjA3MzM1MzA0Nn0.dAuK5FJO3AdqkQoGxvDFDZb1Lv_E2OTxV1JzKLkfpA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});